### ISSUE TITLE
code

### ISSUE THREAD

**Issue by wwjwy** [HiLab-git/WSL4MIS#2]
I cannot find the pCE + Entropy Minimization method in your code, can you help me? Thank you

**Comment by Luoxd1996** [comment]
Hi, Sorry, I will update this code later. Best, Xiangde. Luo xd ***@***.*** 签名由 网易邮箱大师 定制 On 03/31/2021 22:14, wwjwy wrote: I cannot find the pCE + Entropy Minimization method in your code, can you help me? Thank you — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wwjwy** [comment]
> Hi, Sorry, I will update this code later. Best, Xiangde. Luo xd ***@***.*** 签名由 网易邮箱大师 定制 On 03/31/2021 22:14, wwjwy wrote: I cannot find the pCE + Entropy Minimization method in your code, can you help me? Thank you — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much

**Comment by Luoxd1996** [comment]
Hi,
The code has been uploaded.
Best,
Xiangde.
